In [52]:
####Q1

In [6]:
import pandas as pd
import scipy
import numpy as np
from scipy import stats

In [7]:
data = pd.read_csv("C:/Users/krishna/Downloads/Cutlets.csv")

In [8]:
data

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [11]:
data1 = data.rename({'Unit B': 'Unit2'}, axis=1)

In [12]:
data2 = data1.rename({'Unit A': 'Unit1'}, axis=1)

In [13]:
stats.ttest_ind(data2.Unit1,data2.Unit2)

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

In [14]:
#this is 2 sample t test.
#thus H0: No difference in the diameter of cutlet between two units
#and  H1: There is difference between them
#as p value(0.47) > alpha(0.05)
#accept H0, therefore there is no significant difference.

In [58]:
####Q2

In [55]:
ll = pd.read_csv("C:/Users/krishna/Downloads/LabTAT.csv")

In [56]:
stats.f_oneway(ll.iloc[:,0], ll.iloc[:,1],ll.iloc[:,2],ll.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [59]:
#as there are 4 samples we do annova.
#thus H0: TAT of the given reports of the labs are same
#and  H1: TAT of the given reports of the Labs are not same
#as p value is 0 < alpha(0.05)
#accept H1, therefore TAT of the given reports of the Labs are not same.

In [60]:
####Q3

In [61]:
br = pd.read_csv("C:/Users/krishna/Downloads/BuyerRatio.csv")

In [62]:
br

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [63]:
stats.chi2_contingency([br["East"],br["West"],br["North"],br["South"]])

(1.5959455386610577,
 0.6603094907091882,
 3,
 array([[  42.76531299,  442.23468701],
        [ 146.81287862, 1518.18712138],
        [ 131.11756787, 1355.88243213],
        [  72.30424052,  747.69575948]]))

In [64]:
#chisquare test
#thus H0: All proportions are equal
#and  H1: All proportions are not equal
#as p value is 0.66 > alpha(0.05)
#accept H0, therefore All proportions are equal

In [65]:
####Q4

In [66]:
co = pd.read_csv("C:/Users/krishna/Downloads/Costomer+OrderForm.csv")

In [68]:
co

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [77]:
co.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [78]:
co.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [79]:
co.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [80]:
co.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [85]:
res=np.array([[271,267,269,280],[29,33,31,20]])

In [86]:
res

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [88]:
stats.chi2_contingency(res)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [89]:
#chisquare test
#thus H0: customer order forms defective % does not vary by centre
#and  H1: customer order forms defective % does varies by centre
#as p value is 0.27 > alpha(0.05)
#accept H0, customer order forms defective % does not vary by centre.